version: "2"
services:
  server:
    image: "node:8.11.1-slim"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/home/node/app
    expose:
      - "5678"
    ports:
      - 5678:5678
    command: "yarn start"